### ISSUE TITLE
Missing gen_dataset.py script

### ISSUE THREAD

**Issue by graytowne** [criteo-research/CausE#1]
Hi, first of all, I read your paper which is really nice and thanks for releasing the code. However, I cannot find the file 'gen_dataset.py' described in the README file of this repo, so I'm wondering if it is possible for providing this file as well.

**Comment by sbonner0** [comment]
Yes the rest of the code is going through internal review and will be added in due course.

**Comment by CXY573** [comment]
@sbonner0  I want to know that whether we should train more epochs when we using casual embedding.

**Comment by CXY573** [comment]
@graytowne  hi, do you know how to create the dataset now?
